version: "3.8"
services: 
  client:
    build: /client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - /client:/app
      - /client/node_modules
    stdin_open: true
    tty: true